### ISSUE TITLE
How to save the cropped image ?

### ISSUE THREAD

**Issue by rsrini83** [HeikkiDev/XFManualCropControl#1]
Hi,

Thanks for the code and its working nicely. However, i did not find way to save the cropped image. Can you guide me on how to save the image ??

--Srinu

**Comment by HeikkiDev** [comment]
Hi. I used OpenCv to crop the image using the corner coordinates and fix the perspective. I'm unable to guide you using only Android/iOS APIs, sorry.

**Comment by HeikkiDev** [comment]
I updated the repository with a working crop solution using SkiaSharp
